In [1]:
# Importing Libraries
import pandas as pd
from bs4 import BeautifulSoup
import requests
import selenium
from selenium import webdriver
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [2]:
driver=webdriver.Chrome(r"/home/sudhakar/Downloads/chromedriver")
time.sleep(5)

In [3]:
    start_page=670
    end_page=706
    AUTHER=[]
    DATE=[]
    HEADLINE=[]
    DISCRIPTION=[]
    URLS=[]
    for page in range(start_page,end_page):
        
        url = "https://www.ebmnews.com/2019/page/" + str(page)
        driver.get(url)
        
        author = driver.find_elements_by_xpath("//div[@class='post-meta']/a/i")
        for i in author:
            AUTHER.append(i.text)
        
        date = driver.find_elements_by_xpath("//span[@class='time']/time")
        for j in date:
            DATE.append(j.text)
       
        headline = driver.find_elements_by_xpath("//h2[@class='title']/a")
        for j in headline:
            HEADLINE.append(j.text)
       
        discription = driver.find_elements_by_xpath("//div[@class='post-summary']")
        for j in discription:
            DISCRIPTION.append(j.text)
        prod_urls = driver.find_elements_by_xpath("//h2[@class='title']/a")
        for prod in prod_urls:
            URLS.append(prod.get_attribute("href"))

In [4]:
    VERTICAL=[]
    for url in URLS:
        driver.get(url)
        vertical = driver.find_elements_by_xpath("//div[@class='post-meta-wrap clearfix']/div/span[1]/a")
        for i in vertical:
            VERTICAL.append(i.text)

In [5]:
len(VERTICAL),len(URLS),len(DISCRIPTION),len(HEADLINE),len(AUTHER),len(DATE)

(360, 360, 360, 360, 360, 360)

In [6]:
import pandas as pd
EBM_NEWS=pd.DataFrame({})
EBM_NEWS['VERTICAL']=VERTICAL
EBM_NEWS['AUTHER']=AUTHER

EBM_NEWS['DATE']=DATE

EBM_NEWS['HEADLINE']=HEADLINE
EBM_NEWS['DISCRIPTION']=DISCRIPTION
EBM_NEWS

,VERTICAL,AUTHER,DATE,HEADLINE,DISCRIPTION
0,AUTOMOTIVE,Reporter,"Feb 8, 2019",Mahindra & Mahindra quarterly profit falls 11....,Automaker Mahindra & Mahindra Ltd on Friday po...
1,DELHI,Reporter,"Feb 8, 2019",Jaitley criticises Cong for promising to withd...,"New Delhi, Feb 08: Criticising Congress for pr..."
2,WORLD,Reporter,"Feb 8, 2019",EU rejects renegotiating Brexit deal as May ar...,Washington: European Union (EU) has once again...
3,NATIONAL,Reporter,"Feb 8, 2019","Budget 2019-20: Crop loan waiver gets Rs 12,65...",Chief Minister HD Kumaraswamy has set aside Rs...
4,WORLD,Reporter,"Feb 8, 2019",Australian Parliament’s computer network targe...,Canberra: Australia`s parliament had to reset ...
...,...,...,...,...,...
355,ENTERTAINMENT,Reporter,"Jan 22, 2019",Manju Warrier’s first Tamil film will be Dhanu...,Malayalam actress Manju Warrier will make her ...
356,ENTERTAINMENT,Reporter,"Jan 22, 2019","After Taapsee, now Amrita Rao reveals even she...","Recently, Taapsee Pannu was in the news for be..."
357,CRICKET,Reporter,"Jan 22, 2019","Kohli sweeps ICC awards, creates history",Dubai: The peerless Virat Kohli became Tuesday...
358,SPORTS,Reporter,"Jan 22, 2019",English Premier League: Jan Siewert as head coach,"The club announced on Monday, Premier League s..."
359,SPORTS,Reporter,"Jan 22, 2019",Sakshi aims to silence critics,After her first win over Navjot Kaur in the Pr...

In [8]:
EBM_NEWS.to_csv("EBM_NEWS2.csv")